name: email_auth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  async: ^2.11.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  http: ^1.3.0
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^19.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  fl_chart: ^0.71.0
  smooth_page_indicator: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png_images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png_images/
    - assets/firebase_key.json
